<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Produtos</title>

  </head>
  <body>

    <div class="container">
        <div class="row">
        <h1>Página não encontrada</h1>
        </div>
    </div>

    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/jquery.min.js" ></script>
  </body>
</html>