<!DOCTYPE html>
<html lang="pt-br">
    <head>
    
        <meta charset="utf-8">

    </head>

    <body>
        
        <?php require_once __DIR__ . "/header.phtml" ?>

        <?php $this->conteudoView() ?>

        <?php require_once __DIR__ . "/footer.phtml" ?>

        <script src="../libs/js/jquery.min.js"></script>
        <script src="../libs/js/bootstrap.js"></script>

    </body>
</html>