

<?php
// MENSAGEM DE CADASTRADO
if (isset($_GET['cadastrado'])) {
    $status = "danger";
    $mensagem = "Falha ao inserir registro";
    if ($_GET['cadastrado']) {
        $status = "success";
        $mensagem = "Registro inserido com sucesso";
    }
    ?>
    <script type="text/javascript">
        $('#att_Modal').modal('hide')
    </script>  
    <div class="alert alert-dismissible alert-<?= $status ?>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?= $mensagem ?>
    </div>
<?php } ?>


<div id="edit-produto">
    <form id="form-edit-produto" action="/produto/inserir" method="POST" class="form-horizontal" enctype="multipart/form-data">
        <label for="">Imagem:</label>  
        <div id="edit-produto-img">
            <img id='imagemVisual' name='imagemVisual' width='362' src=''>
        </div>

        <div style='margin-bottom:20px;' class="custom-file">
            <input type="file" name='imagem' class="custom-file-input" id="customFile" accept="image/*" onchange="readURL(this);">
            <label class="custom-file-label" for="customFile">Selecionar Nova Imagem</label>
        </div>

        <script>
        // APRESENTA O NOME DA IMAGEM ON SELECT
        $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });

        // APRESENTA A IMAGEM SELECIONADA
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                $('#imagemVisual')
                    .attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        </script>

        <div class="form-group">
            <label for="edit-descricao-produto">Descrição do Produto</label>
            <input name="descricao" type="text" class="form-control" id="edit-descricao-produto" placeholder="Descrição">
            <small id="help" class="form-text text-muted">Por favor, informe apenas descrições válidas.</small>
        </div>
        <div class="form-group">
            <label for="edit-valor-produto">Valor</label>
            <input name="valor" class="form-control" id="edit-valor-produto" placeholder="Valor">
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</div>
