<div id="list" class="row" align="center">
 
 <div class="table col-md-11">
     <table class="table table-striped" cellspacing="1" cellpadding="1">
         <thead>
             <tr>
                 <th>Código</th>
                 <th>Descrição</th>
                 <th>Valor</th>
                 <th class="actions">Ações</th>
              </tr>
         </thead>
         <tbody>
         <?php foreach ($this->view->produtos as $produto): ?>

             <tr>
                 <td><?php echo $produto->getProdutoCodigo(); ?> </td>
                 <td><?php echo $produto->getProdutoDescricao(); ?> </td>
                 <td><?php echo $produto->getProdutoValor(); ?> </td>
                 <td class="actions">
                     <a style="margin-bottom: 10px" class="btn btn-warning btn-xs" href="/produto/<?php echo $produto->getProdutoCodigo(); ?>/listar"><i title="Editar" class="material-icons" data-toggle="tooltip">&#xE254</i></a>
                     <a class="btn btn-danger btn-xs"  href="/produto/<?php echo $produto->getProdutoCodigo(); ?>/deletar" ><i title="Deletar" class="material-icons">&#xE872</i></a>
                 </td>
             </tr>
             <?php endforeach; ?>
         </tbody>
      </table>

  </div>
</div> <!-- /#list -->
